data:
  dataset: caltech256  # you can choose caltech101, caltech256, tiny-imagenet
  split: "8:1:1"
  caltech101:
    root_folder: /home/zhouchen/Datasets/Caltech101/101_ObjectCategories
    txt_path: ../dataset/caltech101/
    classes: 101
  caltech256:
    root_folder: /home/zhouchen/Datasets/Caltech256/256_ObjectCategories
    txt_path: ../dataset/caltech256/
    classes: 257
  tiny-imagenet:
    root_folder: /home/zhouchen/Datasets/tiny-imagenet-200
    txt_path: ../dataset/tiny-imagenet200/
    classes: 200

train:
  model: resnest # resnet, senet, cbam, eca-net, sknet, triplet-attention, resnest
  img_size: 224
  lr: 0.001
  epochs: 50
  bs: 64
  device: cuda:0

exp:
  dir: ../runs/
  name: caltech256-resnest # dataset-model